osx_image: xcode11

language: objective-c
cache:
  - bundler
  - cocoapods

env:
  # Override this variable in the matrix to specify a Swift target name suffix.
  # The variable is used by `./test.sh`
  - SWIFT_SUFFIX=

matrix:
  include:
  - podfile: abtesting/Podfile
    env: SAMPLE=ABTesting
  - podfile: admob/Podfile
    env:
      - SAMPLE=AdMob
      - SWIFT_SUFFIX=Swift
  - podfile: analytics/Podfile
    env: SAMPLE=Analytics
  - podfile: authentication/Podfile
    env: SAMPLE=Authentication
  - podfile: config/Podfile
    env: SAMPLE=Config
  - podfile: crashlytics/Podfile
    env: SAMPLE=Crashlytics
  - podfile: database/Podfile
    env: SAMPLE=Database
  - podfile: dynamiclinks/Podfile
    env: SAMPLE=DynamicLinks
  - podfile: firestore/Podfile
    env: SAMPLE=Firestore
  - podfile: functions/Podfile
    env: SAMPLE=Functions
  - podfile: messaging/Podfile
    env: SAMPLE=InAppMessaging
  - podfile: inappmessaging/Podfile
    env: SAMPLE=Messaging
  - podfile: mlvision/Podfile
    env: SAMPLE=MLVision
  - podfile: performance/Podfile
    env: SAMPLE=Performance
  - podfile: storage/Podfile
    env: SAMPLE=Storage
  - podfile: installations/Podfile
    env: SAMPLE=Installations
  - podfile: installations/Podfile
    env:
      - SAMPLE=Installations
      - SWIFT_SUFFIX=Swift

before_install:
  - cd $SAMPLE
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update
  - ../scripts/install_prereqs/$SAMPLE.sh
  - cd -

script: travis_retry ./scripts/test.sh

branches:
  only:
    - master
