name: A/B Testing

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/abtesting.yml'
      - 'abtesting/**'
      - 'scripts/*'
      - 'scripts/abtesting.sh'
      - '!abtesting/*.md'
      - '!abtesting/Design/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/abtesting.yml'
      - 'abtesting/**'
      - 'scripts/*'
      - 'scripts/abtesting.sh'
      - '!abtesting/*.md'
      - '!abtesting/Design/**'

  workflow_dispatch:

env:
  secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
  SAMPLE: ABTesting

jobs:
  cocoapods:
    name: cocoapods
    runs-on: macOS-latest
    env:
      SPM: false
      TEST: true
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd abtesting/LegacyABTestingQuickstart
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          cd ..
          ../scripts/install_prereqs/abtesting.sh
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          LEGACY: true
          SWIFT_SUFFIX: ""
          OS: iOS
          DEVICE: iPhone 11
  spm:
    name: spm (Xcode ${{ matrix.xcode }} - ${{ matrix.os }})
    runs-on: macOS-11
    strategy:
      matrix:
        xcode: ["12.5", "13.0"]
        os: [iOS, tvOS, macOS, watchOS]
        test: [true]
        include:
          - os: iOS
            device: iPhone 12
          - os: tvOS
            device: Apple TV 4K (at 1080p) (2nd generation)
          - os: macOS
            device: localhost
          - os: watchOS
            device: Apple Watch Series 5 - 44m
            test: false
        exclude:
          - os: watchOS
            test: true
    env:
      SPM: true
      DIR: abtesting
      OS: ${{ matrix.os }}
      DEVICE: ${{ matrix.device }}
      TEST: ${{ matrix.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          sudo xcode-select -s "/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer"
          gem install xcpretty
          cd abtesting
          ../scripts/install_prereqs/abtesting.sh
        env:
          XCODE_VERSION: ${{ matrix.xcode }}
      - name: Build and Test SwiftUI (${{ matrix.os }})
        run: ./scripts/test.sh
