name: A/B Testing

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/abtesting.yml'
      - 'abtesting/**'
      - 'scripts/*'
      - 'scripts/abtesting.sh'
      - '!abtesting/*.md'
      - '!abtesting/Design/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/abtesting.yml'
      - 'abtesting/**'
      - 'scripts/*'
      - 'scripts/abtesting.sh'
      - '!abtesting/*.md'
      - '!abtesting/Design/**'

  workflow_dispatch:

env:
  secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
  SAMPLE: ABTesting

jobs:
  cocoapods:
    name: cocoapods
    runs-on: macOS-latest
    env:
      SPM: false
      TEST: true
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd abtesting/LegacyABTestingQuickstart
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          cd ..
          ../scripts/install_prereqs/abtesting.sh
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          LEGACY: true
          SWIFT_SUFFIX: ""
          OS: iOS
          DEVICE: iPhone 11
  spm:
    name: spm (Xcode ${{ matrix.xcode }} - ${{ matrix.os }})
    strategy:
      matrix:
        host_os: [macOS-11, macOS-10.15]
        os: [iOS, tvOS, macOS, watchOS, catalyst]
        include:
          - os: iOS
            device: iPhone 12
            test: true
          - os: tvOS
            device: Apple TV 4K (at 1080p) (2nd generation)
            test: true
          - os: macOS
            device: localhost
            test: true
          - os: watchOS
            device: Apple Watch Series 5 - 44m
            test: false
          - os: catalyst
            device: localhost
            test: true
    runs-on: ${{ matrix.host_os }}
    env:
      SETUP: abtesting
      SPM: true
      DIR: abtesting
      OS: ${{ matrix.os }}
      DEVICE: ${{ matrix.device }}
      TEST: ${{ matrix.test }}
      XCODE_VERSION: ${{ matrix.xcode }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Xcode 12.5 for macOS-10.5
        if: matrix.host_os == 'macOS-10.15'
        run: sudo xcode-select -s "/Applications/Xcode_12.5.app/Contents/Developer"
      - name: Setup
        run: |
          gem install xcpretty
          cd $SETUP
          ../scripts/install_prereqs/${SETUP}.sh
      - name: Build and Test SwiftUI (${{ matrix.os }})
        run: ./scripts/test.sh
