name: A/B Testing

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/abtesting.yml'
      - 'abtesting/**'
      - 'scripts/*'
      - 'scripts/abtesting.sh'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/abtesting.yml'
      - 'abtesting/**'
      - 'scripts/*'
      - 'scripts/abtesting.sh'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd abtesting/LegacyABTestingQuickstart
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          cd ..
          ../scripts/install_prereqs/abtesting.sh
        env:
          SAMPLE: ABTesting
          secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
          LEGACY: true
      - name: Build Swift
        run: |
          ./scripts/test.sh
        env:
          SAMPLE: ABTesting
          LEGACY: true
      - name: Build and Test SwiftUI
        run: |
          cd scripts
          source install_prereqs/abtesting.sh
          cd ..
          source scripts/test_spm.sh
        env:
          SAMPLE: ABTesting
          DIR: abtesting
          OS: iOS
          PLATFORM: iphone
          DEVICE: iPhone 11
          SWIFT_DEFINES: ""
          secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
