name: Authentication

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/authentication.yml'
      - 'authentication/**'
      - 'scripts/*'
      - 'scripts/authentication.sh'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/authentication.yml'
      - 'authentication/**'
      - 'scripts/*'
      - 'scripts/authentication.sh'

  workflow_dispatch:

env:
  SAMPLE: Authentication
  secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}

jobs:
  cocoapods:
    name: cocoapods
    runs-on: macOS-12
    env:
      SPM: false
      LEGACY: false
      OS: iOS
      DEVICE: iPhone 11
      TEST: false
    steps:
      - name: Checkout
        uses: actions/checkout@master
      # Facebook SDK 12.0.1 requires Xcode 13
      - name: Xcode 13.3.1
        run: sudo xcode-select -s /Applications/Xcode_13.3.1.app/Contents/Developer
      - name: Setup
        run: |
          cd authentication
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/authentication.sh
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ""
