name: firebaseai

permissions:
  contents: read

on:
  pull_request:
    paths:
    - 'firebaseai/**'
    - '.github/workflows/firebaseai.yml'
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  SAMPLE: FirebaseAI

jobs:
  spm:
    name: spm (Xcode ${{ matrix.xcode }} - ${{ matrix.platform }})
    strategy:
      matrix:
        include:
          - os: macos-15
            xcode: "16.4"
            platform: iOS
            device: iPhone 16
            ios_version: "18"
          - os: macos-26
            xcode: "26.0"
            platform: iOS
            device: iPhone 16e
            ios_version: "26"
    runs-on: ${{ matrix.os }}
    env:
      SETUP: firebaseai
      SPM: true
      DIR: firebaseai
      OS: ${{ matrix.platform }}
      DEVICE: ${{ matrix.device }}
      TEST: false
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Setup
        run: |
          gem install xcpretty
      - name: Placeholder GoogleService-Info.plist good enough for build only testing.
        run: cp ./mock-GoogleService-Info.plist ./firebaseai/GoogleService-Info.plist
      - name: Build and Test SwiftUI (${{ matrix.platform }})
        run: ./scripts/test.sh
