name: Functions

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/functions.yml'
      - 'functions/**'
      - 'scripts/*'
      - 'scripts/functions.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/functions.yml'
      - 'functions/**'
      - 'scripts/*'
      - 'scripts/functions.sh'

  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

env:
  SAMPLE: Functions
  secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}

jobs:
  spm:
    name: spm (Xcode ${{ matrix.xcode }} - ${{ matrix.os }})
    runs-on: macOS-15
    strategy:
      matrix:
        xcode: ["16.4"]
        os: [iOS, tvOS, macOS]
        include:
          - os: iOS
            device: iPhone 16
          - os: tvOS
            device: Apple TV 4K (3rd generation) (at 1080p)
          - os: macOS
            device: localhost
    env:
      SETUP: functions
      SPM: true
      DIR: functions/FunctionsExample
      OS: ${{ matrix.os }}
      DEVICE: ${{ matrix.device }}
      TEST: false
<<<<<<< Updated upstream
      XCODE_VERSION: ${{ matrix.xcode }}
=======
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
>>>>>>> Stashed changes
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          gem install xcpretty
          cd $SETUP
          ../scripts/install_prereqs/${SETUP}.sh
      - name: Build and Test SwiftUI (${{ matrix.os }})
        run: ./scripts/test.sh
